export const translations = {
  zh: {
    code: "编程",
    art: "绘画",
    writing: "写作",
    video: "视频",
    scratch: "Scratch",
    maker: "手工实验",
    achievement: "证书活动",
    original: "原创",
    all: "全部"
  },
  en: {
    code: "Code",
    art: "Art",
    writing: "Writing",
    video: "Video",
    scratch: "Scratch",
    maker: "Maker",
    achievement: "Achievement",
    original: "Original",
    all: "All"
  }
};

export const sampleWorks = [
  {
    id: "pixel-adventure",
    slug: "pixel-adventure",
    type: "code",
    category: "code",
    title_zh: "像素冒险小游戏",
    title_en: "Pixel Adventure Game",
    summary_zh: "基于 JavaScript 的横版闯关，包含积分、碰撞和关卡状态。",
    summary_en: "A JavaScript side-scroller with scoring, collision, and level states.",
    content_zh: "重点训练了角色移动、碰撞检测、关卡进度和键盘交互。",
    content_en: "The project focuses on movement, collision detection, level progression, and keyboard control.",
    tags: ["JavaScript", "Game", "Canvas"],
    cover_image: "",
    cover_style: "linear-gradient(135deg, #00a6b8, #8ec63f)",
    gallery_images: [],
    media_url: "",
    code_url: "#",
    demo_url: "#",
    materials: [],
    process_steps: [
      { title: "Character System", detail: "Set up movement and sprite states." },
      { title: "Collision", detail: "Added tile and enemy collision logic." }
    ],
    learning_notes: "学会了把复杂功能拆成多个小模块逐步实现。",
    parent_note: "持续迭代能力很明显，建议下一步加入音效系统。",
    featured: true,
    sort_order: 1,
    is_published: true,
    published_at: "2026-05-01",
    author_role: "child",
    created_at: "2026-05-01T00:00:00.000Z",
    updated_at: "2026-05-01T00:00:00.000Z"
  },
  {
    id: "sunset-sketch",
    slug: "sunset-sketch",
    type: "art",
    category: "art",
    title_zh: "海边日落速写",
    title_en: "Seaside Sunset Sketch",
    summary_zh: "水彩分层表现天空和海面的光影变化。",
    summary_en: "A watercolor study of light transitions over sea and sky.",
    content_zh: "从铅笔构图到上色分层，练习光源方向和冷暖对比。",
    content_en: "From pencil composition to layered paint, focusing on light direction and warm/cool contrast.",
    tags: ["Watercolor", "Sketch", "Light"],
    cover_image: "",
    cover_style: "linear-gradient(135deg, #f05d4f, #f3b61f)",
    gallery_images: [],
    media_url: "",
    code_url: "",
    demo_url: "",
    materials: ["水彩纸", "24 色颜料", "中号平头刷"],
    process_steps: [
      { title: "Base Layer", detail: "先铺天色和海面底色。" },
      { title: "Contrast", detail: "增加前景暗部和人物剪影。" }
    ],
    learning_notes: "在同一幅画里尝试更明显的明暗关系。",
    parent_note: "",
    featured: true,
    sort_order: 2,
    is_published: true,
    published_at: "2026-04-18",
    author_role: "child",
    created_at: "2026-04-18T00:00:00.000Z",
    updated_at: "2026-04-18T00:00:00.000Z"
  },
  {
    id: "echo-station",
    slug: "echo-station",
    type: "writing",
    category: "writing",
    title_zh: "科幻短篇《回声站》",
    title_en: "Short Story: Echo Station",
    summary_zh: "围绕太空信号展开的成长主题短篇。",
    summary_en: "A coming-of-age sci-fi short story around a deep-space signal.",
    content_zh: "故事尝试把科学想象和成长选择放在同一个冲突里，后续会补插图版。",
    content_en: "The story places science fiction and growth choices in one conflict, with an illustrated revision planned.",
    tags: ["Writing", "Sci-fi", "Story"],
    cover_image: "",
    cover_style: "linear-gradient(135deg, #7b61ff, #00a6b8)",
    gallery_images: [],
    media_url: "",
    code_url: "",
    demo_url: "",
    materials: [],
    process_steps: [],
    learning_notes: "第一次把故事拆成三幕再回填细节。",
    parent_note: "人物动机清晰，后续可以加强环境描写。",
    featured: false,
    sort_order: 10,
    is_published: true,
    published_at: "2026-03-22",
    author_role: "child",
    created_at: "2026-03-22T00:00:00.000Z",
    updated_at: "2026-03-22T00:00:00.000Z"
  },
  {
    id: "weather-dashboard",
    slug: "weather-dashboard",
    type: "scratch",
    category: "scratch",
    title_zh: "天气互动看板",
    title_en: "Weather Interactive Board",
    summary_zh: "用可视化模块搭建天气展示与交互切换。",
    summary_en: "A visual weather board with interactive state switching.",
    content_zh: "包含城市切换、天气图标和趋势展示，是后续数据项目的基础。",
    content_en: "Includes city switching, weather icons, and trend display as a base for future data projects.",
    tags: ["Scratch", "Dashboard", "Data"],
    cover_image: "",
    cover_style: "linear-gradient(135deg, #16202a, #00a6b8)",
    gallery_images: [],
    media_url: "#",
    code_url: "",
    demo_url: "#",
    materials: [],
    process_steps: [],
    learning_notes: "",
    parent_note: "",
    featured: false,
    sort_order: 20,
    is_published: true,
    published_at: "2026-02-10",
    author_role: "child",
    created_at: "2026-02-10T00:00:00.000Z",
    updated_at: "2026-02-10T00:00:00.000Z"
  }
];

export function localizedField(work, field, lang = "zh") {
  return work[`${field}_${lang}`] || work[`${field}_zh`] || "";
}
